<div class="row">
	<div class="col-md-3 col-sm-4" user-panel="account" hide-header="true"></div>
	<div class="col-md-9 col-sm-8">
		<form name="passwordForm" class="block block-light" ng-submit="save()">
			<header class="section header">
				<h1>Change Your Password</h1>
			</header>
			<div class="alert alert-danger" ng-if="error">
				{{error}}
			</div>
			<div class="alert alert-success" ng-if="success">
				Your password has been changed successfully
			</div>
			<section class="section body">
				<div class="form-group">
					<label>Current Password</label>
					<input type="password" class="form-control" name="currentPassword" ng-model="currentPassword" autocomplete="off" required>
				</div>
				<div class="form-group">
					<label>New Password</label>
					<input type="password" class="form-control" name="newPassword" ng-model="newPassword" autocomplete="off" required>
				</div>
				<div class="form-group">
					<label>Confirm New Password</label>
					<input type="password" class="form-control" name="newPasswordConfirm" ng-model="newPasswordConfirm" autocomplete="off" required>
				</div>
			</section>
			<footer class="section footer" ng-if="!passwordForm.$pristine">
				<div class="row">
					<div class="col-xs-6">
						<input type="submit" class="btn btn-lg btn-primary btn-block" value="Save">
					</div>
					<div class="col-xs-6">
						<input type="reset" class="btn btn-lg btn-danger btn-block" value="Cancel" ng-click="reset()">
					</div>
				</div>
			</footer>
		</form>
	</div>
</div>