<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<form name="newUser" class="block" action="./account/sign-up.json" method="post" target="resultWindow" ng-submit="submit()">
			<header class="section header">
				<h1>Create An Account</h1>
			</header>
			<section class="alert alert-danger" ng-if="error">
				<p class="lead">{{error.message}}</p>
			</section>
			<section class="alert alert-success" ng-if="user.isActive">
				<p class="lead">Welcome, {{user.nickname}}!</p>
				<p>Please wait while you're redirected</p>
			</section>
			<section class="section body">
				<div class="form-group" ng-class="{'has-error':hasError('username')}">
					<label class="control-label">Username</label>
					<input type="text" class="form-control input-lg" name="user[username]" ng-model="user.username" required>
					<span class="help-block" ng-if="hasError('username')" ng-bind="getError('username')"></span>
				</div>
				<div class="form-group" ng-class="{'has-error':hasError('nickname')}">
					<label class="control-label">Display Name</label>
					<input type="text" class="form-control input-lg" name="user[nickname]" ng-model="user.nickname" required>
					<span class="help-block" ng-if="hasError('nickname')" ng-bind="getError('nickname')"></span>
				</div>
				<div class="form-group" ng-class="{'has-error':hasError('email')}">
					<label class="control-label">Email Address</label>
					<input type="email" class="form-control input-lg" name="user[email]" ng-model="user.email" required>
					<span class="help-block" ng-if="hasError('email')" ng-bind="getError('email')"></span>
				</div>
				<div class="form-group" ng-class="{'has-error':hasError('password')}">
					<label class="control-label">Password</label>
					<input type="password" class="form-control input-lg" name="user[password]" ng-model="user.password" required>
					<span class="help-block" ng-if="hasError('password')" ng-bind="getError('password')"></span>
				</div>
				<div class="form-group" ng-class="{'has-error':hasError('passwordConfirm')}">
					<label class="control-label">Confirm Password</label>
					<input type="password" class="form-control input-lg" name="user[passwordConfirm]" ng-model="user.passwordConfirm" required>
					<span class="help-block" ng-if="hasError('passwordConfirm')" ng-bind="getError('passwordConfirm')"></span>
				</div>
			</section>
			<footer class="section footer">
				<ul class="controls pull-right" ng-if="acl.canSignIn">
					<li>
						<a href="./account/sign-in" class="btn btn-default">Sign In</a>
					</li>
				</ul>
				<input type="submit" class="btn btn-primary" value="Create Account">
				<input type="hidden" name="formatResponse" value="0">
			</footer>
		</form>
	</div>
</div>
<iframe name="resultWindow" id="resultWindow" style="height: 0; visibility: hidden;"></iframe>