<div id="account-sign-in">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<form class="block block-light" method="post" action="./account/sign-in.json" target="resultWindow" ng-submit="submit()">
				<header class="section header">
					<h1>Sign In</h1>
				</header>
				<section class="alert alert-danger" ng-if="error">
					<p class="lead">{{error.message}}</p>
				</section>
				<section class="alert alert-success" ng-if="user">
					<p class="lead">Welcome back, {{user.nickname}}!</p>
					<p>Please wait while you're redirected</p>
				</section>
				<section class="section body">
					<div class="form-group">
						<label>Username/Email</label>
						<input type="text" class="form-control input-lg" name="username" required>
					</div>
					<div class="form-group">
						<label>Password</label>
						<input type="password" class="form-control input-lg" name="password" required>
					</div>
				</section>
				<footer class="section footer">
					<ul class="controls pull-right" ng-if="acl.canSignUp">
						<li>
							<a href="./account/sign-up" class="btn btn-default">Create An Account</a>
						</li>
					</ul>
					<input type="submit" class="btn btn-primary" value="Sign In">
					<input type="hidden" name="formatResponse" value="0">
				</footer>
			</form>
		</div>
	</div>
	<iframe name="resultWindow" id="resultWindow" style="visibility: hidden; height: 0;"></iframe>
</div>