<form class="row" ng-submit="save()" ng-if="!user.id">
	<div class="col-md-8">
		<div class="block block-light">
			<header class="section header">
				<h1>New User</h1>
			</header>
			<section class="section body">
				<div class="row">
					<div class="col-sm-6">
						<div class="form-group">
							<label>Email Address</label>
							<input type="email" class="form-control" name="user[email]" ng-model="user.email" required>
						</div>
						<div class="form-group">
							<label>Username</label>
							<input type="text" class="form-control" name="user[username]" ng-model="user.username" required>
						</div>
						<div class="form-group">
							<label>Password</label>
							<input type="password" class="form-control" name="user[password]" ng-model="user.password" required>
						</div>
						<div class="form-group">
							<label>Role</label>
							<select class="form-control" name="user[role]" ng-model="user.role">
								<option value="user">Standard User</option>
								<option value="admin">Administrator</option>
							</select>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="form-group">
							<label>First Name</label>
							<input type="text" class="form-control" name="user[firstName]" ng-model="user.firstName">
						</div>
						<div class="form-group">
							<label>Last Name</label>
							<input type="text" class="form-control" name="user[lastName]" ng-model="user.lastName">
						</div>
						<div class="form-group">
							<label>Display Name</label>
							<input type="text" class="form-control" name="user[nickname]" ng-model="user.nickname" required>
						</div>
					</div>
				</div>
			</section>
			<footer class="section footer">
				<input type="submit" class="btn btn-block btn-lg btn-primary" value="Create">
			</footer>
		</div>
	</div>
</form>

<div class="row" ng-if="user.id">
	<div class="col-md-8">
		<div class="block block-light">
			<header class="section header">
				<h1>Success</h1>
				<h3>
					<a href="./{{user.path}}">
						<strong>{{user.nickname}}</strong>
					</a> 
					has been created successfully!
				</h3>
			</header>
			<footer class="section footer">
				<div class="row">
					<div class="col-sm-6">
						<a href="./users" class="btn btn-lg btn-primary btn-block">
							User List
						</a>
					</div>
					<div class="col-sm-6">
						<button class="btn btn-lg btn-success btn-block" ng-click="reset()">
							New User
						</button>
					</div>
				</div>
			</footer>
		</div>
	</div>
</div>